"""some changes made to testDrive model

Revision ID: 52a125bc29ec
Revises: c7b5c0ce167c
Create Date: 2026-03-26 19:14:17.752855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a125bc29ec'
down_revision: Union[str, Sequence[str], None] = 'c7b5c0ce167c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_drives', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('test_drives', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('test_drives', sa.Column('phone', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('test_drives_customer_id_fkey'), 'test_drives', type_='foreignkey')
    op.drop_column('test_drives', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_drives', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('test_drives_customer_id_fkey'), 'test_drives', 'customers', ['customer_id'], ['id'])
    op.drop_column('test_drives', 'phone')
    op.drop_column('test_drives', 'email')
    op.drop_column('test_drives', 'full_name')
    # ### end Alembic commands ###
