"""added customer name in sale for walk-ins

Revision ID: 6ff2ce3e8b12
Revises: 8b4926e7536a
Create Date: 2026-03-29 12:52:38.186131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff2ce3e8b12'
down_revision: Union[str, Sequence[str], None] = '8b4926e7536a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_name', sa.String(length=100), nullable=True))
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales', 'customer_name')
    # ### end Alembic commands ###
