"""added inventory_id to the carMedia table

Revision ID: 7b0f2b9d2d5e
Revises: b9ba5b3edcda
Create Date: 2026-03-28 19:37:46.062560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0f2b9d2d5e'
down_revision: Union[str, Sequence[str], None] = 'b9ba5b3edcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_media', sa.Column('inventory_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('car_media_car_id_fkey'), 'car_media', type_='foreignkey')
    op.create_foreign_key(None, 'car_media', 'inventory', ['inventory_id'], ['id'])
    op.drop_column('car_media', 'car_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_media', sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'car_media', type_='foreignkey')
    op.create_foreign_key(op.f('car_media_car_id_fkey'), 'car_media', 'cars', ['car_id'], ['id'])
    op.drop_column('car_media', 'inventory_id')
    # ### end Alembic commands ###
