"""made the inventory_id not nullable

Revision ID: 8b4926e7536a
Revises: 7b0f2b9d2d5e
Create Date: 2026-03-28 19:44:29.908245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4926e7536a'
down_revision: Union[str, Sequence[str], None] = '7b0f2b9d2d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_media', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_media', 'inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
