"""some changes made to customer and test drvie model

Revision ID: b9ba5b3edcda
Revises: 52a125bc29ec
Create Date: 2026-03-27 12:26:50.628168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ba5b3edcda'
down_revision: Union[str, Sequence[str], None] = '52a125bc29ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
