"""initial_migration

Revision ID: c7b5c0ce167c
Revises: 
Create Date: 2026-03-26 18:59:22.161705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b5c0ce167c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('segment', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_created_at'), 'cars', ['created_at'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_make'), 'cars', ['make'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_verification_sent', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('car_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('wheelbase_mm', sa.Integer(), nullable=True),
    sa.Column('ground_clearance_mm', sa.Integer(), nullable=True),
    sa.Column('curb_weight_kg', sa.Integer(), nullable=True),
    sa.Column('fuel_tank_l', sa.Integer(), nullable=True),
    sa.Column('boot_space_l', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('tyre_size', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_index(op.f('ix_car_dimensions_id'), 'car_dimensions', ['id'], unique=False)
    op.create_table('car_engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('displacement_cc', sa.Integer(), nullable=True),
    sa.Column('horsepower', sa.Integer(), nullable=True),
    sa.Column('torque_nm', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('transmission_gears', sa.Integer(), nullable=True),
    sa.Column('drivetrain', sa.String(length=10), nullable=True),
    sa.Column('fuel_economy_l100', sa.Float(), nullable=True),
    sa.Column('top_speed_kmh', sa.Integer(), nullable=True),
    sa.Column('acceleration_sec', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_index(op.f('ix_car_engine_id'), 'car_engine', ['id'], unique=False)
    op.create_table('car_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('sunroof', sa.Boolean(), nullable=True),
    sa.Column('panoramic_roof', sa.Boolean(), nullable=True),
    sa.Column('heated_seats', sa.Boolean(), nullable=True),
    sa.Column('ventilated_seats', sa.Boolean(), nullable=True),
    sa.Column('leather_seats', sa.Boolean(), nullable=True),
    sa.Column('memory_seats', sa.Boolean(), nullable=True),
    sa.Column('heated_steering_wheel', sa.Boolean(), nullable=True),
    sa.Column('apple_carplay', sa.Boolean(), nullable=True),
    sa.Column('android_auto', sa.Boolean(), nullable=True),
    sa.Column('wireless_charging', sa.Boolean(), nullable=True),
    sa.Column('keyless_entry', sa.Boolean(), nullable=True),
    sa.Column('push_start', sa.Boolean(), nullable=True),
    sa.Column('remote_start', sa.Boolean(), nullable=True),
    sa.Column('heads_up_display', sa.Boolean(), nullable=True),
    sa.Column('infotainment_screen_inch', sa.Float(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=True),
    sa.Column('premium_audio', sa.Boolean(), nullable=True),
    sa.Column('led_headlights', sa.Boolean(), nullable=True),
    sa.Column('adaptive_headlights', sa.Boolean(), nullable=True),
    sa.Column('ambient_lighting', sa.Boolean(), nullable=True),
    sa.Column('power_tailgate', sa.Boolean(), nullable=True),
    sa.Column('power_mirrors', sa.Boolean(), nullable=True),
    sa.Column('auto_dimming_mirror', sa.Boolean(), nullable=True),
    sa.Column('cruise_control', sa.Boolean(), nullable=True),
    sa.Column('adaptive_cruise_control', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_index(op.f('ix_car_features_id'), 'car_features', ['id'], unique=False)
    op.create_table('car_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_media_id'), 'car_media', ['id'], unique=False)
    op.create_table('car_safety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('ncap_rating', sa.Integer(), nullable=True),
    sa.Column('airbag_count', sa.Integer(), nullable=True),
    sa.Column('abs', sa.Boolean(), nullable=True),
    sa.Column('esp', sa.Boolean(), nullable=True),
    sa.Column('traction_control', sa.Boolean(), nullable=True),
    sa.Column('hill_start_assist', sa.Boolean(), nullable=True),
    sa.Column('hill_descent_control', sa.Boolean(), nullable=True),
    sa.Column('lane_keep_assist', sa.Boolean(), nullable=True),
    sa.Column('lane_departure_warning', sa.Boolean(), nullable=True),
    sa.Column('blind_spot_monitor', sa.Boolean(), nullable=True),
    sa.Column('rear_cross_traffic_alert', sa.Boolean(), nullable=True),
    sa.Column('forward_collision_warning', sa.Boolean(), nullable=True),
    sa.Column('auto_emergency_braking', sa.Boolean(), nullable=True),
    sa.Column('traffic_sign_recognition', sa.Boolean(), nullable=True),
    sa.Column('rear_camera', sa.Boolean(), nullable=True),
    sa.Column('surround_view_camera', sa.Boolean(), nullable=True),
    sa.Column('parking_sensors_front', sa.Boolean(), nullable=True),
    sa.Column('parking_sensors_rear', sa.Boolean(), nullable=True),
    sa.Column('self_parking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    op.create_index(op.f('ix_car_safety_id'), 'car_safety', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('preferred_car_types', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('stock_number', sa.String(length=30), nullable=True),
    sa.Column('exterior_color', sa.String(length=30), nullable=True),
    sa.Column('interior_color', sa.String(length=30), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('new', 'used', 'refurbished', name='unit_condition'), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'sold', 'maintenance', name='inventory_status'), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('discounted_price', sa.Float(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('stock_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_inventory_car_id'), 'inventory', ['car_id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('sale_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('test_drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_drives_id'), 'test_drives', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_test_drives_id'), table_name='test_drives')
    op.drop_table('test_drives')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_inventory_status'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_car_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_car_safety_id'), table_name='car_safety')
    op.drop_table('car_safety')
    op.drop_index(op.f('ix_car_media_id'), table_name='car_media')
    op.drop_table('car_media')
    op.drop_index(op.f('ix_car_features_id'), table_name='car_features')
    op.drop_table('car_features')
    op.drop_index(op.f('ix_car_engine_id'), table_name='car_engine')
    op.drop_table('car_engine')
    op.drop_index(op.f('ix_car_dimensions_id'), table_name='car_dimensions')
    op.drop_table('car_dimensions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_make'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_created_at'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
